#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# miki: set brew's openjdk@17 to be the default
export PATH="/usr/local/opt/openjdk@17/bin:$PATH"
# miki: set brew's ant to be the default
export PATH="/usr/local/opt/ant@1.9/bin:$PATH"
# miki: emacs build / configure-script needs 'makeinfo >= 4.13'
#       -> replaced by 'brew install texinfo' + adding it to PATH before /usr/bin
export PATH="/usr/local/opt/texinfo/bin:$PATH"
