#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# miki:
# - set brew's openjdk@21 to be the default
# - set brew's ant to be the default
# - emacs build / configure-script needs 'makeinfo >= 4.13'
#   -> replaced by 'brew install texinfo' + adding it to PATH before /usr/bin
export JAVA_HOME=/opt/homebrew/opt/openjdk@21
export ANTPATH=/opt/homebrew/opt/ant@1.10/bin
TEXINFOPATH=/opt/homebrew/opt/texinfo/bin
export PATH=$JAVA_HOME:$PATH
export PATH=$ANTPATH:$PATH
export PATH=$TEXINFOPATH:$PATH

eval "$(~/.local/bin/mise activate zsh)"
